@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Jharoka Website Final V1"
echo Renaming branch...
git branch -M main
echo Adding remote...
git remote add origin https://github.com/varuntejreddy03/Jharoka.git
echo Pushing...
git push -u origin main
echo Done!
pause
